### ISSUE TITLE
[ NAV ] 리팩토링

### ISSUE THREAD

**Issue by MinaRoh** [FESI-4-4/slid-todo#218]
## 이슈 내용
Nav 가 열렸을때, 닫혔을때를 각각 컴포넌트로 만들었는데, 애니메이션을 적용하려고 하니 전체적으로 리팩토링이 필요할 것 같습니다.

## ✅ To Dos
- [x] 전체 구조 리팩토링
- [x] nav 열림 상태에서 태블릿 화면으로 조정시 생기는 nav 디자인 오류 수정
- [x] 파일 이름 확인
- [x] 중복 제거
- [x] nav 관련 스크롤바 제거 - #247 에서 해결
- [x] 접힌 nav 펼치기 버튼 hover시 cursor 스타일 추가 - #248 에서 해결
- [x] nav 열림 초기값 데스크탑-열림/ 나머지-닫힘 #239 에서 해결
